Homework-16: Point
ebagirov/EmilBagirov_JavaBasic_12.10.2023 pull request #7
Opened 2023-11-03 11:45 UTC by ebagirov

Updated coordinates are not printed.

2023-11-04 14:38 UTC, JIeIIIa requested changes

2023-11-04 14:38 UTC, JIeIIIa commented on src/homework/hw16/Point.java
> +        if (this == o) return true;
Це не відповідає нашим домовленостям (code conventions): навіть якщо один оператор відноситься до if мають бути фігурні дужки

2023-11-04 14:38 UTC, JIeIIIa commented on src/homework/hw16/Point.java
> +    protected Object clone() throws CloneNotSupportedException {
В класі `Object` метод описано так `protected Object clone()` Але ж якщо ти викликаєш його в іншому класі, то `clone` має повертати обʼєкт класу, у якому описано. На лекції це було. 
Також доцільно зробити метод публічним щоб його міг викликати будь-хто

2023-11-04 15:53 UTC, ebagirov commented on src/homework/hw16/Point.java
> +        if (this == o) return true;
Виправлено, додано фігурні дужки:
   
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Point point)) {
            return false;
        }
        return x == point.x && y == point.y;
    }

2023-11-04 16:01 UTC, ebagirov commented on src/homework/hw16/Point.java
> +    protected Object clone() throws CloneNotSupportedException {
Виправлено:
- змінено модифікатор доступу на public;
- змінено об'єкт класу на конкретний, а саме на Point$
- в return statement відповідно додано (Point).

    @Override
    public Point clone() throws CloneNotSupportedException {
        return (Point) super.clone();
    }

2023-11-05 09:28 UTC, JIeIIIa approved these changes

2023-11-11 13:03 UTC, ebagirov commented
Merge pull request #7 from ebagirov/Homework-16 to Main.

2023-11-11 13:04 UTC, merged